name: 构建可执行文件
run-name: 构建可执行文件
on: [push]

jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v2

      - name: 初始化 python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - run: pip install -r requirements.txt

      - name: 构建可执行文件
        run: python setup.py build

      - name: 上传文件
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/

  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v2

      - name: 初始化 python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - run: pip install -r requirements.txt

      - name: 构建可执行文件
        run: python setup.py build

      - name: 上传文件
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/