on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: '检查 GitHub Action'
      uses: actions/checkout@v4

    - name: 初始化 Python ${{ env.PYTHON_VERSION }} 环境
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: '使用 pip 安装依赖'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: '构建发行'
      shell: bash
      run: |
        python setup.py build

    - name: 上传文件
      uses: actions/upload-artifact@v2
      with:
        name: DDNetToolBox-linux
        path: dist

  build-windows:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: '检查 GitHub Action'
      uses: actions/checkout@v4

    - name: 初始化 Python ${{ env.PYTHON_VERSION }} 环境
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: '使用 pip 安装依赖'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: '构建发行'
      shell: bash
      run: |
        python setup.py build

    - name: 上传文件
      uses: actions/upload-artifact@v2
      with:
        name: DDNetToolBox-linux
        path: dist