on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # macos-latest
    runs-on: ${{ matrix.os }}
    environment: dev
    steps:
    - name: '签出仓库'
      uses: actions/checkout@v4

    - name: 初始化 Python ${{ env.PYTHON_VERSION }} 环境
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: '使用 pip 安装依赖'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install imageio

    - name: '构建发行'
      shell: bash
      run: |
        ${{ matrix.os == 'macos-latest' && 'python setup.py build' || 'python setup.py build macos' }}

    - name: 上传文件
      uses: actions/upload-artifact@v2
      with:
        name: DDNetToolBox-${{ runner.os }}-dev-${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        path: ${{ matrix.os == 'ubuntu-latest' && 'build/main.bin' || (matrix.os == 'windows-latest' && 'build/main.exe' || 'build/main.bin') }}